load("//build/bzl:python.bzl", "o_py_library", "o_py_test")

o_py_library(
    name = "interfaces_lib",
    srcs = ["interfaces.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//mlody/core:query_spec_lib",
        "@pip//pyarrow",
    ],
)

o_py_library(
    name = "location_specs_lib",
    srcs = ["location_specs.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":csv_source_lib",
        ":interfaces_lib",
        ":materialized_local_source_lib",
        ":parquet_source_lib",
        "//mlody/core/assets:interfaces_lib",
        "//mlody/core/assets:resolution_lib",
        "//mlody/core:location_specs_lib",
        "//mlody/core:query_spec_lib",
        "//mlody/core/sql:sql_query_lib",
    ],
)

o_py_library(
    name = "remote_staging_lib",
    srcs = ["remote_staging.py"],
    visibility = ["//:__subpackages__"],
    deps = ["//mlody/core/assets:http_asset_lib"],
)

o_py_library(
    name = "parquet_source_lib",
    srcs = ["parquet_source.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":interfaces_lib",
        "//mlody/core/sql:sql_query_lib",
        "@pip//pyarrow",
    ],
)

o_py_library(
    name = "csv_source_lib",
    srcs = ["csv_source.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":interfaces_lib",
        "//mlody/core/sql:sql_query_lib",
        "@pip//pyarrow",
    ],
)

o_py_library(
    name = "materialized_local_source_lib",
    srcs = ["materialized_local_source.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":csv_source_lib",
        ":interfaces_lib",
        ":parquet_source_lib",
        "//mlody/core/assets:copied_asset_lib",
        "//mlody/core/assets:interfaces_lib",
    ],
)

o_py_library(
    name = "derived_source_lib",
    srcs = ["derived_source.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":interfaces_lib",
        ":location_specs_lib",
        ":parquet_source_lib",
        "//mlody/core:optimiser",
        "//mlody/core/sql:sql_query_lib",
        "@pip//pyarrow",
    ],
)

o_py_library(
    name = "tabular",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":csv_source_lib",
        ":derived_source_lib",
        ":interfaces_lib",
        ":location_specs_lib",
        ":materialized_local_source_lib",
        ":parquet_source_lib",
        ":remote_staging_lib",
    ],
)

o_py_library(
    name = "tabular_lib",
    srcs = [
        "__init__.py",
        "csv_source.py",
        "derived_source.py",
        "interfaces.py",
        "location_specs.py",
        "materialized_local_source.py",
        "parquet_source.py",
        "remote_staging.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":derived_source_lib",
        ":interfaces_lib",
        ":location_specs_lib",
        ":parquet_source_lib",
        "//mlody/core:core_lib",
        "//mlody/core/assets:copied_asset_lib",
        "//mlody/core/assets:interfaces_lib",
        "//mlody/core/sql:sql_query_lib",
        "@pip//pyarrow",
    ],
)

o_py_test(
    name = "location_specs_test",
    srcs = ["location_specs_test.py"],
    deps = [
        ":location_specs_lib",
        ":tabular",
        "//mlody/common:common_lib",
        "@pip//pyarrow",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "parquet_source_test",
    srcs = ["parquet_source_test.py"],
    deps = [
        ":parquet_source_lib",
        "@pip//pyarrow",
    ],
)

o_py_test(
    name = "csv_source_test",
    srcs = ["csv_source_test.py"],
    deps = [
        ":tabular",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "derived_source_test",
    srcs = ["derived_source_test.py"],
    deps = [
        ":derived_source_lib",
        ":location_specs_lib",
        "//mlody/core:query_spec_lib",
        "@pip//pyarrow",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "remote_staging_test",
    srcs = ["remote_staging_test.py"],
    deps = [
        "//mlody/core/assets:http_asset_lib",
        ":tabular",
        "@pip//pytest",
    ],
)
