"""Tests for the public setf API skeleton."""

from __future__ import annotations

from pathlib import Path

import pytest
from pyfakefs.fake_filesystem import FakeFilesystem

from common.python.starlarkish.core.struct import Struct

from mlody.core.anchor import RegistryEntityAnchor
from mlody.core.setf import can_setf, resolve_places, setf, setf_root
from mlody.core.setf_strategies import (
    DictKeySetter,
    ListIndexSetter,
    ReadOnlyFieldSetter,
    StructFieldSetter,
    VirtualValueFieldSetter,
)
from mlody.core.traversal_grammar import FieldSegment, IndexSegment, KeySegment, PathExpression
from mlody.core.virtual_value import make_virtual_value
from mlody.core.workspace import Workspace


# Real source files required by workspace_loader Phase 1; added to fake filesystems.
_REAL_RULE_MLODY = Path(__file__).parent / "rule.mlody"
_REAL_MM_MLODY = Path(__file__).parent.parent / "common" / "mm.mlody"
_REAL_HASH_MLODY = Path(__file__).parent.parent / "common" / "hash.mlody"
_REAL_RENDER_MLODY = Path(__file__).parent.parent / "common" / "render.mlody"
_REAL_CONFIG_MLODY = Path(__file__).parent.parent / "common" / "config.mlody"


_STRING_TYPE = Struct(kind="type", type="string", name="string")
_WORKSPACE_INFO_TYPE = Struct(
    kind="type",
    type="workspace_info",
    name="workspace_info",
    _root_kind="record",
    fields=[
        Struct(name="branch", type=_STRING_TYPE),
        Struct(name="sha", type=_STRING_TYPE),
    ],
)

_WORKSPACE_ROOT = Path("/workspace")
_BUILTINS_MLODY = """\
def root(name, path, description=""):
    entity_type = None
    try:
        entity_type = builtins.lookup("type", "mlody-root")
    except:
        entity_type = None
    fields = {
        "name": name,
        "path": path,
        "description": description,
    }
    if entity_type != None:
        fields["_entity_type"] = entity_type
    builtins.register("root", struct(**fields))
"""
_ROOTS_MLODY = """\
load("//mlody/core/builtins.mlody", "root")

root(name="lexica", path="//mlody/teams/lexica", description="team root")
"""
_TYPES_MLODY = """\
# Register mm.vector so render.mlody can use mm.vector(...) patterns.
# After task 7.1, mm.vector is no longer a fixed attr on MmNamespace;
# it is auto-generated by typedef(name="vector", ...) in the real types.mlody.
builtins.register_mm_pattern("type", "vector", {"element_type": None})

def _validate_line_number(v):
    if not isinstance(v, int) or isinstance(v, bool):
        raise TypeError("expected integer line number")
    return True

builtins.register("type", struct(
    kind="type", type="line_number", name="line_number",
    validator=_validate_line_number,
    attributes={}, _allowed_attrs={},
))
builtins.register("type", struct(
    kind="type", type="mlody-source-range", name="mlody-source-range",
    fields=[
        struct(name="filepath", type=struct(kind="type", type="string", name="string")),
        struct(name="start_line", type=builtins.lookup("type", "line_number")),
        struct(name="end_line", type=builtins.lookup("type", "line_number")),
    ],
    attributes={}, _allowed_attrs={},
    _root_kind="record",
))
builtins.register("type", struct(
    kind="type", type="mlody_workspace_info", name="mlody_workspace_info",
    fields=[
        struct(name="path", type=struct(kind="type", type="string", name="string")),
        struct(name="branch", type=struct(kind="type", type="string", name="string")),
        struct(name="sha", type=struct(kind="type", type="string", name="string")),
        struct(name="roots", type=struct(kind="type", type="vector", name="vector")),
    ],
    attributes={}, _allowed_attrs={},
    _root_kind="record",
))
_ENTITY_FIELDS = [
    struct(name="_source_range", type=builtins.lookup("type", "mlody-source-range"), mandatory=False),
]
builtins.register("type", struct(
    kind="type", type="mlody-value", name="mlody-value",
    fields=_ENTITY_FIELDS,
    attributes={}, _allowed_attrs={},
    _root_kind="record",
))
builtins.register("type", struct(
    kind="type", type="mlody-task", name="mlody-task",
    fields=_ENTITY_FIELDS + [
        struct(
            name="_hash",
            type=struct(kind="type", type="string", name="string"),
            materializer=lambda _task: python.uuid7(),
        ),
    ],
    attributes={}, _allowed_attrs={},
    _root_kind="record",
))
builtins.register("type", struct(
    kind="type", type="mlody-action", name="mlody-action",
    fields=_ENTITY_FIELDS,
    attributes={}, _allowed_attrs={},
    _root_kind="record",
))
builtins.register("type", struct(
    kind="type", type="mlody-root", name="mlody-root",
    fields=_ENTITY_FIELDS,
    attributes={}, _allowed_attrs={},
    _root_kind="record",
))
builtins.register("type", struct(
    kind="type", type="mlody-workspace", name="mlody-workspace",
    fields=_ENTITY_FIELDS + [
        struct(name="info", type=struct(kind="type", type="mlody_workspace_info", name="mlody_workspace_info", _root_kind="record", fields=[
            struct(name="path", type=struct(kind="type", type="string", name="string")),
            struct(name="branch", type=struct(kind="type", type="string", name="string")),
            struct(name="sha", type=struct(kind="type", type="string", name="string")),
            struct(name="roots", type=struct(kind="type", type="vector", name="vector")),
        ])),
    ],
    attributes={}, _allowed_attrs={},
))
"""


def _create_workspace_project(
    fs: FakeFilesystem,
    root: Path,
    *,
    api_sha: str = "old-api",
    web_sha: str = "old-web",
) -> Path:
    fs.create_file(str(root / "mlody/core/builtins.mlody"), contents=_BUILTINS_MLODY)
    fs.create_file(str(root / "mlody/roots.mlody"), contents=_ROOTS_MLODY)
    fs.create_file(str(root / "mlody/common/types.mlody"), contents=_TYPES_MLODY)
    # mm.mlody, render.mlody, config.mlody, and rule.mlody are required by workspace_loader Phase 1.
    fs.add_real_file(_REAL_RULE_MLODY, target_path=str(root / "mlody/core/rule.mlody"))
    fs.add_real_file(_REAL_MM_MLODY, target_path=str(root / "mlody/common/mm.mlody"))
    fs.add_real_file(_REAL_HASH_MLODY, target_path=str(root / "mlody/common/hash.mlody"))
    fs.add_real_file(_REAL_RENDER_MLODY, target_path=str(root / "mlody/common/render.mlody"))
    fs.add_real_file(_REAL_CONFIG_MLODY, target_path=str(root / "mlody/common/config.mlody"))
    fs.create_file(
        str(root / "mlody/teams/lexica/services/release/api/image.mlody"),
        contents=f"""\
builtins.register("value", Struct(
    kind="value",
    name="image",
    config=Struct(commit_sha="{api_sha}"),
    _lineage=[],
    _source_range=Struct(
        kind="mlody-source-range",
        filepath="mlody/teams/lexica/services/release/api/image.mlody",
        start_line=10,
        end_line=11,
        _entity_type=builtins.lookup("type", "mlody-source-range"),
    ),
))
""",
    )
    fs.create_file(
        str(root / "mlody/teams/lexica/services/release/web/image.mlody"),
        contents=f"""\
builtins.register("value", Struct(
    kind="value",
    name="image",
    config=Struct(commit_sha="{web_sha}"),
    _lineage=[],
    _source_range=Struct(
        kind="mlody-source-range",
        filepath="mlody/teams/lexica/services/release/web/image.mlody",
        start_line=20,
        end_line=21,
        _entity_type=builtins.lookup("type", "mlody-source-range"),
    ),
))
""",
    )
    fs.create_file(
        str(root / "mlody/teams/lexica/services/broken/image.mlody"),
        contents="""\
builtins.register("value", Struct(
    kind="value",
    name="image",
    config=Struct(version="1"),
    _lineage=[],
    _source_range=Struct(
        kind="mlody-source-range",
        filepath="mlody/teams/lexica/services/broken/image.mlody",
        start_line=30,
        end_line=31,
        _entity_type=builtins.lookup("type", "mlody-source-range"),
    ),
))
""",
    )
    return root


@pytest.fixture()
def workspace_project(fs: FakeFilesystem) -> Path:
    return _create_workspace_project(fs, _WORKSPACE_ROOT)


@pytest.fixture()
def loaded_workspace(workspace_project: Path) -> Workspace:
    ws = Workspace(monorepo_root=workspace_project)
    ws.load()
    return ws


def _virtual_workspace_info() -> Struct:
    return make_virtual_value(
        value_type=_WORKSPACE_INFO_TYPE,
        label="'info",
        materializer=lambda _value: Struct(branch="main", sha="abc123"),
    )


class TestSetfModuleSkeleton:
    """Foundation tests for the public setf API surface."""

    def test_resolve_places_parses_string_selector_for_struct_fields(self) -> None:
        """Task 2.2 / 2.3: string selectors reuse the traversal parser."""
        root = Struct(config=Struct(learning_rate=0.1))

        place_set = resolve_places(root, ".config.learning_rate")

        assert len(place_set.places) == 1
        place = place_set.places[0]
        assert str(place.selector) == ".config.learning_rate"
        assert place.accessor == ".config.learning_rate"
        assert place.current_value == 0.1
        assert isinstance(place.strategy, StructFieldSetter)

    def test_resolve_places_accepts_path_expression_without_reparsing(self) -> None:
        """Task 2.2: PathExpression selectors are accepted directly."""
        selector = PathExpression(
            segments=(FieldSegment("config"), FieldSegment("learning_rate"))
        )
        root = Struct(config=Struct(learning_rate=0.1))

        place_set = resolve_places(root, selector)

        assert len(place_set.places) == 1
        assert place_set.places[0].selector == selector

    def test_resolve_places_marks_slice_selection_as_projected(self) -> None:
        """Task 3.4: slice selections resolve to one projected place."""
        root = Struct(items=[0, 1, 2, 3])

        place_set = resolve_places(root, ".items[::2]")

        assert len(place_set.places) == 1
        place = place_set.places[0]
        assert place.projected is True
        assert place.accessor == ".items[::2]"
        assert place.current_value == [0, 2]

    def test_resolve_places_expands_wildcard_into_multiple_direct_places(self) -> None:
        """Task 3.5: wildcard expansion returns one place per child."""
        root = Struct(outputs=Struct(left=1, right=2))

        place_set = resolve_places(root, ".outputs[*]")

        assert [place.accessor for place in place_set.places] == [
            ".outputs.left",
            ".outputs.right",
        ]

    def test_resolve_places_expands_recursive_descent_into_matching_places(self) -> None:
        """Task 3.6: recursive descent returns all matching descendants."""
        root = Struct(
            first=Struct(sha="a"),
            second=Struct(inner=Struct(sha="b")),
        )

        place_set = resolve_places(root, "...sha")

        assert [place.accessor for place in place_set.places] == [
            ".first.sha",
            ".second.inner.sha",
        ]

    def test_resolve_places_traverses_declared_virtual_fields(self) -> None:
        """Task 6.1: virtual values expose declared child places to setf."""
        root = _virtual_workspace_info()

        place_set = resolve_places(root, ".branch")

        assert len(place_set.places) == 1
        place = place_set.places[0]
        assert place.accessor == ".branch"
        assert getattr(place.current_value, "kind", None) == "value"
        assert getattr(getattr(place.current_value, "location", None), "type", None) == "virtual"
        assert getattr(place.current_value, "label", None) == "'info.branch"

    def test_resolve_places_expands_recursive_descent_through_virtual_values(self) -> None:
        """Task 6.1: recursive descent can enumerate declared virtual children."""
        root = Struct(info=_virtual_workspace_info())

        place_set = resolve_places(root, "...branch")

        assert [place.accessor for place in place_set.places] == [".info.branch"]

    def test_can_setf_accepts_valid_direct_struct_field_assignment(self) -> None:
        """Task 4.3: can_setf preflights a valid direct field write."""
        root = Struct(config=Struct(learning_rate=0.1))

        can_setf(root, ".config.learning_rate", 0.2)

    def test_can_setf_rejects_virtual_value_targets_until_strategy_exists(self) -> None:
        """Task 6.1: virtual targets fail explicitly during write preflight."""
        root = _virtual_workspace_info()

        with pytest.raises(NotImplementedError, match="virtual value selectors"):
            can_setf(root, ".branch", "release")

    def test_can_setf_rejects_read_only_runtime_method_targets(self) -> None:
        """Synthetic method attributes are readable but not assignable."""
        root = Struct(
            kind="location",
            type="inline",
            name="inline",
            methods=Struct(
                info=lambda owner, _enclosing=None: f"location: {owner.name}",
            ),
        )

        with pytest.raises(NotImplementedError, match="read-only runtime selectors"):
            can_setf(root, ".info", "override")

    def test_setf_updates_direct_struct_field_without_mutating_original(self) -> None:
        """Task 3.1 / 4.4: direct Struct field writes rebuild the path safely."""
        root = Struct(config=Struct(learning_rate=0.1))

        updated = setf_root(root, ".config.learning_rate", 0.2)

        assert updated.config.learning_rate == 0.2
        assert root.config.learning_rate == 0.1

    def test_setf_updates_list_index_inside_struct(self) -> None:
        """Task 3.2 / 4.4: direct list index writes are supported."""
        root = Struct(items=[1, 2, 3])

        updated = setf_root(root, ".items[1]", 99)

        assert updated.items == [1, 99, 3]
        assert root.items == [1, 2, 3]

    def test_setf_updates_nested_dict_key_path(self) -> None:
        """Task 3.3 / 4.4: direct dict key writes are supported."""
        root = {"config": {"learning_rate": 0.1}}

        updated = setf_root(root, '["config"]["learning_rate"]', 0.2)

        assert updated["config"]["learning_rate"] == 0.2
        assert root["config"]["learning_rate"] == 0.1

    def test_setf_updates_projected_slice_without_mutating_original(self) -> None:
        """Task 3.4 / 4.4: projected slice writes update every selected index."""
        root = Struct(items=[0, 1, 2, 3, 4])

        updated = setf_root(root, ".items[::2]", 42)

        assert updated.items == [42, 1, 42, 3, 42]
        assert root.items == [0, 1, 2, 3, 4]

    def test_setf_updates_all_places_selected_by_recursive_descent(self) -> None:
        """Task 3.6 / 4.4: recursive-descent bulk writes update all matches."""
        root = Struct(
            first=Struct(sha="old"),
            second=Struct(inner=Struct(sha="old")),
        )

        updated = setf_root(root, "...sha", "new")

        assert updated.first.sha == "new"
        assert updated.second.inner.sha == "new"
        assert root.first.sha == "old"
        assert root.second.inner.sha == "old"

    def test_setf_fails_before_any_write_on_heterogeneous_bulk_targets(self) -> None:
        """Task 4.5 / 4.6: bulk writes abort before commit on mixed contracts."""
        root = Struct(
            values=[
                Struct(type="integer", representation="plain", payload=1),
                Struct(type="string", representation="plain", payload="x"),
            ]
        )

        with pytest.raises(ValueError, match="uniform declared type"):
            setf_root(root, ".values[*]", Struct(payload="new"))

        assert root.values[0].payload == 1
        assert root.values[1].payload == "x"

    def test_setf_appends_lineage_to_direct_selected_value(self) -> None:
        """Task 5.3 / 5.4: direct writes append lineage to the updated value."""
        root = Struct(config=Struct(value=1, _lineage=[]))
        replacement = Struct(value=2, _lineage=[])

        updated = setf_root(
            root,
            ".config",
            replacement,
            source="tester",
            reason="bump",
            timestamp="2026-04-20T00:00:00Z",
        )

        assert len(updated.config._lineage) == 1
        event = updated.config._lineage[0]
        assert event.accessor == ".config"
        assert event.new_value == replacement
        assert event.source == "tester"

    def test_setf_appends_projected_lineage_to_aggregate_owner(self) -> None:
        """Task 5.5: projected writes preserve the aggregate accessor in lineage."""
        root = {"items": [0, 1, 2, 3], "_lineage": []}

        updated = setf_root(
            root,
            '["items"][::2]',
            42,
            source="tester",
            reason="mask",
            timestamp="2026-04-20T00:00:00Z",
        )

        assert updated["items"] == [42, 1, 42, 3]
        assert len(updated["_lineage"]) == 1
        event = updated["_lineage"][0]
        assert event.accessor == '["items"][::2]'
        assert event.source == "tester"

    def test_setf_appends_lineage_to_owner_when_child_has_no_lineage(self) -> None:
        """Direct child writes fall back to the owner's lineage sink."""
        root = Struct(
            location=Struct(type="inline", data="before"),
            _lineage=[],
        )

        updated = setf_root(
            root,
            ".location",
            Struct(type="inline", data="after"),
            source="tester",
            reason="override",
            timestamp="2026-05-05T00:00:00Z",
        )

        assert updated.location.data == "after"
        assert len(updated._lineage) == 1
        event = updated._lineage[0]
        assert event.accessor == ".location"
        assert event.source == "tester"

    def test_setf_creates_missing_allowed_struct_field(self) -> None:
        """Terminal field writes may create a declared-but-absent child."""
        root = Struct(
            config=Struct(
                _allowed_attrs={"sha": Struct(name="sha", type=_STRING_TYPE)},
            )
        )

        updated = setf_root(root, ".config.sha", "new-sha")

        assert updated.config.sha == "new-sha"
        assert not hasattr(root.config, "sha")

    def test_resolve_places_raises_for_missing_struct_field(self) -> None:
        """Task 3.7: missing field selections fail immediately."""
        root = Struct(config=Struct(learning_rate=0.1))

        with pytest.raises(AttributeError):
            resolve_places(root, ".config.missing")

    def test_setf_raises_for_out_of_bounds_index(self) -> None:
        """Task 3.7: missing index targets fail immediately."""
        root = Struct(items=[1, 2])

        with pytest.raises(IndexError):
            setf_root(root, ".items[5]", 99)

    def test_setf_raises_for_missing_dict_key(self) -> None:
        """Task 3.7: missing dict-key targets fail immediately."""
        root = {"config": {"learning_rate": 0.1}}

        with pytest.raises(KeyError):
            setf_root(root, '["config"]["missing"]', 0.2)


class TestWorkspaceFirstSetf:
    """Workspace-first label-aware `setf` acceptance tests."""

    def test_selector_from_label_anchor_expands_inline_dict_keys(self) -> None:
        from mlody.core.setf import _selector_from_label_anchor

        selector = _selector_from_label_anchor(
            RegistryEntityAnchor(
                root_value=Struct(kind="task", name="downloader"),
                registry_key=("task", "mlody/common/huggingface/downloader", "downloader"),
                field_parts=('action["info"]', "implementation"),
            )
        )

        assert selector == PathExpression(
            segments=(
                FieldSegment("action"),
                KeySegment("info"),
                FieldSegment("implementation"),
            )
        )

    def test_setf_updates_unqualified_label_against_explicit_workspace(
        self, loaded_workspace: Workspace
    ) -> None:
        updated_workspace = setf(
            "@lexica//services/release/api/image:image.config.commit_sha",
            "new-api",
            workspace=loaded_workspace,
        )

        assert updated_workspace is loaded_workspace
        assert (
            updated_workspace.resolve(
                "@lexica//services/release/api/image:image.config.commit_sha"
            )
            == "new-api"
        )

    def test_setf_uses_cwd_workspace_for_unqualified_labels(
        self,
        monkeypatch: pytest.MonkeyPatch,
        workspace_project: Path,
    ) -> None:
        monkeypatch.chdir(workspace_project)

        updated_workspace = setf(
            "@lexica//services/release/api/image:image.config.commit_sha",
            "cwd-sha",
        )

        assert (
            updated_workspace.resolve(
                "@lexica//services/release/api/image:image.config.commit_sha"
            )
            == "cwd-sha"
        )

    def test_setf_rejects_explicit_workspace_qualifiers(
        self, loaded_workspace: Workspace
    ) -> None:
        with pytest.raises(ValueError, match="relative to the current workspace"):
            setf(
                "main|@lexica//services/release/api/image:image.config.commit_sha",
                "resolved-sha",
                workspace=loaded_workspace,
            )

    def test_setf_uses_expand_wildcard_label_and_preserves_transactionality(
        self,
        loaded_workspace: Workspace,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        calls: list[str] = []
        real_expand = loaded_workspace.expand_wildcard_label

        def _record_expand(inner_label: str) -> list[str]:
            calls.append(inner_label)
            _ = real_expand
            return [
                "@lexica//services/release/api/image:image.config.commit_sha",
                "@lexica//services/release/web/image:image.config.commit_sha",
                "@lexica//services/broken/image:image.config.commit_sha",
            ]

        monkeypatch.setattr(loaded_workspace, "expand_wildcard_label", _record_expand)

        with pytest.raises(AttributeError):
            setf(
                "@lexica//services/...:image.config.commit_sha",
                "bulk-sha",
                workspace=loaded_workspace,
            )

        assert calls == ["@lexica//services/...:image.config.commit_sha"]
        assert (
            loaded_workspace.resolve(
                "@lexica//services/release/api/image:image.config.commit_sha"
            )
            == "old-api"
        )
        assert (
            loaded_workspace.resolve(
                "@lexica//services/release/web/image:image.config.commit_sha"
            )
            == "old-web"
        )

    def test_setf_lowers_entity_field_path_into_root_engine(
        self, loaded_workspace: Workspace
    ) -> None:
        setf(
            "@lexica//services/release/web/image:image.config.commit_sha",
            "field-path-sha",
            workspace=loaded_workspace,
        )

        entity = loaded_workspace.resolve("@lexica//services/release/web/image:image")
        assert entity.config.commit_sha == "field-path-sha"

    def test_setf_updates_workspace_declared_attribute(self, loaded_workspace: Workspace) -> None:
        from mlody.core.workspace import force

        setf("'info.branch", "release", workspace=loaded_workspace)

        assert loaded_workspace.info.branch == "release"
        assert force(loaded_workspace.resolve("'info.branch")) == "release"

    def test_setf_updates_entity_source_range_leaf(self, loaded_workspace: Workspace) -> None:
        setf(
            "@lexica//services/release/api/image:image._source_range.start_line",
            777,
            workspace=loaded_workspace,
        )

        entity = loaded_workspace.resolve("@lexica//services/release/api/image:image")
        assert entity._source_range.start_line == 777  # type: ignore[attr-defined]
        assert (
            loaded_workspace.resolve(
                "@lexica//services/release/api/image:image._source_range.start_line"
            )
            == 777
        )

    def test_setf_validates_entity_source_range_leaf_type(
        self, loaded_workspace: Workspace
    ) -> None:
        with pytest.raises(TypeError):
            setf(
                "@lexica//services/release/api/image:image._source_range.start_line",
                "oops",
                workspace=loaded_workspace,
            )


class TestMakeDirectPlaceStrategySelection:
    """F11: _make_direct_place selects the correct strategy via _STRATEGIES loop.

    Tests are written against resolve_places() since _make_direct_place is private.
    The strategy is accessible via place.strategy.
    """

    def test_resolve_places_selects_virtual_value_setter_for_virtual_owner(self) -> None:
        # Spec scenario: _make_direct_place selects VirtualValueFieldSetter for virtual owner
        root = _virtual_workspace_info()

        place_set = resolve_places(root, ".branch")

        assert len(place_set.places) == 1
        assert isinstance(place_set.places[0].strategy, VirtualValueFieldSetter)

    def test_resolve_places_selects_read_only_setter_for_readonly_runtime_attr(self) -> None:
        # Spec scenario: _make_direct_place selects ReadOnlyFieldSetter for read-only runtime attr
        root = Struct(
            kind="location",
            type="inline",
            name="inline",
            methods=Struct(
                info=lambda owner, _enclosing=None: f"location: {owner.name}",
            ),
        )

        place_set = resolve_places(root, ".info")

        assert len(place_set.places) == 1
        assert isinstance(place_set.places[0].strategy, ReadOnlyFieldSetter)

    def test_resolve_places_selects_struct_field_setter_for_struct_owner(self) -> None:
        # Spec scenario: _make_direct_place selects StructFieldSetter for struct owner
        root = Struct(config=Struct(lr=0.1))

        place_set = resolve_places(root, ".config.lr")

        assert len(place_set.places) == 1
        assert isinstance(place_set.places[0].strategy, StructFieldSetter)

    def test_resolve_places_selects_dict_key_setter_for_dict_owner_with_key_segment(self) -> None:
        # Spec scenario: _make_direct_place selects DictKeySetter for dict owner + KeySegment
        root = {"config": {"lr": 0.1}}

        place_set = resolve_places(root, '["config"]["lr"]')

        assert len(place_set.places) == 1
        assert isinstance(place_set.places[0].strategy, DictKeySetter)

    def test_resolve_places_selects_list_index_setter_for_list_owner(self) -> None:
        # Spec scenario: _make_direct_place selects ListIndexSetter for list owner + IndexSegment
        root = Struct(items=[1, 2, 3])

        place_set = resolve_places(root, ".items[0]")

        assert len(place_set.places) == 1
        assert isinstance(place_set.places[0].strategy, ListIndexSetter)

    def test_resolve_places_raises_not_implemented_for_unsupported_combination(self) -> None:
        # Spec scenario: raises NotImplementedError for unsupported (seg, owner) pair
        # A plain int owner with a FieldSegment has no matching strategy.
        # We need to construct this case directly via resolve_places on a nested path
        # that terminates on an int owner — that triggers _make_direct_place failure.
        root = Struct(n=42)

        # .n.x would try to navigate into an int owner with FieldSegment("x")
        with pytest.raises((NotImplementedError, AttributeError)):
            resolve_places(root, ".n.x")
