load("//build/bzl:python.bzl", "o_py_library", "o_py_test")

o_py_library(
    name = "tests_lib",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
)

o_py_test(
    name = "errors_test",
    srcs = ["errors_test.py"],
    deps = [
        "//common/python/errors:errors_lib",
        "@pip//pytest",
    ],
)
