# gazelle:resolve py mlody.teams.framera.pose_estimation //mlody/teams/framera/pose_estimation:framera_lib
# gazelle:resolve py mlody.teams.framera.pose_estimation.calibration //mlody/teams/framera/pose_estimation:framera_lib
# gazelle:resolve py mlody.teams.framera.pose_estimation.camera_calibrate //mlody/teams/framera/pose_estimation:framera_lib
# gazelle:resolve py mlody.teams.framera.pose_estimation.geometry //mlody/teams/framera/pose_estimation:framera_lib
# gazelle:resolve py mlody.teams.framera.pose_estimation.mediapipe_adapter //mlody/teams/framera/pose_estimation:framera_lib
# gazelle:resolve py mlody.teams.framera.pose_estimation.pose_estimator //mlody/teams/framera/pose_estimation:framera_lib
# gazelle:resolve py mlody.teams.framera.pose_estimation.runtime //mlody/teams/framera/pose_estimation:framera_lib
# gazelle:resolve py mlody.teams.framera.pose_estimation.schema //mlody/teams/framera/pose_estimation:framera_lib
load("//build/bzl:python.bzl", "o_py_binary", "o_py_library", "o_py_test")

o_py_library(
    name = "framera_lib",
    srcs = [
        "__init__.py",
        "calibration.py",
        "camera_calibrate.py",
        "geometry.py",
        "mediapipe_adapter.py",
        "pose_estimator.py",
        "runtime.py",
        "schema.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//mlody:mlody_lib",
        "@pip//click",
        "@pip//mediapipe",
        "@pip//numpy",
        "@pip//opencv_python",
    ],
)

o_py_binary(
    name = "framera_pose_estimator",
    srcs = ["pose-estimator.py"],
    main = "pose-estimator.py",
    package_collisions = "warning",
    visibility = ["//visibility:public"],
    deps = [":framera_lib"],
)

o_py_binary(
    name = "framera_camera_calibrate",
    srcs = ["calibrate-camera.py"],
    data = ["calibration-chessboard-9x6-25mm.svg"],
    main = "calibrate-camera.py",
    package_collisions = "warning",
    visibility = ["//visibility:public"],
    deps = [":framera_lib"],
)

o_py_test(
    name = "framera_test",
    srcs = [
        "calibration_test.py",
        "camera_calibrate_test.py",
        "geometry_test.py",
        "mediapipe_adapter_test.py",
        "pose_estimator_test.py",
        "runtime_test.py",
        "schema_test.py",
    ],
    package_collisions = "warning",
    visibility = ["//visibility:public"],
    deps = [
        ":framera_lib",
        "@pip//click",
        "@pip//numpy",
    ],
)

o_py_binary(
    name = "camera_calibrate",
    srcs = ["camera_calibrate.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pip//click",
        "@pip//numpy",
        "@pip//opencv_python",
    ],
)

o_py_binary(
    name = "pose_estimator",
    srcs = ["pose_estimator.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//click"],
)

o_py_library(
    name = "pose_estimation_lib",
    srcs = [
        "__init__.py",
        "calibrate-camera.py",
        "calibration.py",
        "camera_calibrate.py",
        "geometry.py",
        "mediapipe_adapter.py",
        "pose-estimator.py",
        "pose_estimator.py",
        "runtime.py",
        "schema.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":framera_lib",
        "@pip//click",
        "@pip//mediapipe",
        "@pip//numpy",
        "@pip//opencv_python",
    ],
)

o_py_test(
    name = "calibration_test",
    srcs = ["calibration_test.py"],
    package_collisions = "warning",
    deps = [
        ":framera_lib",
        "@pip//numpy",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "camera_calibrate_test",
    srcs = ["camera_calibrate_test.py"],
    package_collisions = "warning",
    deps = [
        ":framera_lib",
        "@pip//click",
        "@pip//numpy",
    ],
)

o_py_test(
    name = "geometry_test",
    srcs = ["geometry_test.py"],
    package_collisions = "warning",
    deps = [
        ":framera_lib",
        "@pip//numpy",
    ],
)

o_py_test(
    name = "mediapipe_adapter_test",
    srcs = ["mediapipe_adapter_test.py"],
    package_collisions = "warning",
    deps = [
        ":framera_lib",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "pose_estimator_test",
    srcs = ["pose_estimator_test.py"],
    package_collisions = "warning",
    deps = [
        ":framera_lib",
        "@pip//click",
    ],
)

o_py_test(
    name = "runtime_test",
    srcs = ["runtime_test.py"],
    package_collisions = "warning",
    deps = [":framera_lib"],
)

o_py_test(
    name = "schema_test",
    srcs = ["schema_test.py"],
    package_collisions = "warning",
    deps = [":framera_lib"],
)
