load("//build/bzl:python.bzl", "o_py_library", "o_py_test")

o_py_library(
    name = "metadata_lib",
    srcs = ["metadata.py"],
    visibility = ["//:__subpackages__"],
)

o_py_library(
    name = "interfaces_lib",
    srcs = ["interfaces.py"],
    visibility = ["//:__subpackages__"],
    deps = [":metadata_lib"],
)

o_py_library(
    name = "manifest_lib",
    srcs = ["manifest.py"],
    visibility = ["//:__subpackages__"],
    deps = [":metadata_lib"],
)

o_py_library(
    name = "cache_lib",
    srcs = ["cache.py"],
    visibility = ["//:__subpackages__"],
)

o_py_library(
    name = "freshness_policy_lib",
    srcs = ["freshness_policy.py"],
    visibility = ["//:__subpackages__"],
    deps = [":manifest_lib"],
)

o_py_library(
    name = "http_asset_lib",
    srcs = ["http_asset.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":cache_lib",
        ":freshness_policy_lib",
        ":interfaces_lib",
        ":manifest_lib",
        ":metadata_lib",
        "//common/python:http_info_lib",
    ],
)

o_py_library(
    name = "local_asset_lib",
    srcs = ["local_asset.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":interfaces_lib",
        ":metadata_lib",
    ],
)

o_py_library(
    name = "copied_asset_lib",
    srcs = ["copied_asset.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":freshness_policy_lib",
        ":interfaces_lib",
        ":metadata_lib",
        "//mlody/common:common_lib",
        "//mlody/core:lineage",
    ],
)

o_py_library(
    name = "resolution_lib",
    srcs = ["resolution.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":copied_asset_lib",
        ":http_asset_lib",
        ":interfaces_lib",
        ":local_asset_lib",
        "//mlody/common:common_lib",
        "//mlody/core:lineage",
        "//mlody/core:location_specs_lib",
    ],
)

o_py_library(
    name = "assets",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":cache_lib",
        ":copied_asset_lib",
        ":freshness_policy_lib",
        ":http_asset_lib",
        ":interfaces_lib",
        ":local_asset_lib",
        ":manifest_lib",
        ":metadata_lib",
        ":resolution_lib",
    ],
)

o_py_test(
    name = "manifest_test",
    srcs = ["manifest_test.py"],
    deps = [
        "//mlody/core:core_lib",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "http_asset_test",
    srcs = ["http_asset_test.py"],
    deps = [
        "//mlody/common:common_lib",
        "//mlody/core:core_lib",
        "//mlody/db:db_lib",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "asset_resolution_test",
    srcs = ["asset_resolution_test.py"],
    deps = [
        "//mlody/common:common_lib",
        "//mlody/core:core_lib",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "copied_asset_test",
    srcs = ["copied_asset_test.py"],
    deps = [
        "//common/python/starlarkish/core:core_lib",
        "//mlody/core:core_lib",
        "@pip//pytest",
    ],
)

o_py_test(
    name = "freshness_policy_test",
    srcs = ["freshness_policy_test.py"],
    deps = [
        "//mlody/common:common_lib",
        "//mlody/core:core_lib",
    ],
)

o_py_library(
    name = "assets_lib",
    srcs = [
        "__init__.py",
        "cache.py",
        "copied_asset.py",
        "freshness_policy.py",
        "http_asset.py",
        "interfaces.py",
        "local_asset.py",
        "manifest.py",
        "metadata.py",
        "resolution.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//common/python:http_info_lib",
        "//mlody/common:common_lib",
        "//mlody/core:core_lib",
        "//mlody/db:db_lib",
    ],
)
