#!/usr/bin/env bash
# Ehi, Emacs, this is -*- shell-script -*-

# After adding a new third-party dependency, developers should run this script.
set -o errexit -o nounset -o pipefail

bazel run //requirements:runtime.update
bazel run //requirements:requirements.all.update
bazel run //:gazelle_python_manifest.update
