#!/usr/bin/env bash
# Ehi, Emacs, this is -*- shell-script -*-

# After adding a new third-party dependency, developers should run this script.
set -o errexit -o nounset -o pipefail

pnpm install --lockfile-only
bazel run @npm//:sync

bazel run //requirements:runtime.update
bazel run //requirements:chatterbox.update
bazel run //requirements:requirements.all.update
bazel run //:gazelle_python_manifest.update
