load("//build/bzl:python.bzl", "o_py_binary", "o_py_library", "o_py_test")

o_py_library(
    name = "sonora_speak_lib",
    srcs = [
        "__init__.py",
        "runtime.py",
        "speak.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pip//click",
        "@pip//kokoro",
        "@pip//numpy",
    ],
)

o_py_binary(
    name = "sonora_speak",
    srcs = ["speak.py"],
    main = "speak.py",
    package_collisions = "warning",
    visibility = ["//visibility:public"],
    deps = ["@pip//click"],
)

o_py_test(
    name = "sonora_speak_test",
    srcs = [
        "runtime_test.py",
        "speak_test.py",
    ],
    package_collisions = "warning",
    deps = [
        ":sonora_speak_lib",
        "@pip//click",
        "@pip//numpy",
    ],
)

o_py_test(
    name = "runtime_test",
    srcs = ["runtime_test.py"],
    deps = [
        ":sonora_speak_lib",
        "@pip//numpy",
    ],
)

o_py_test(
    name = "speak_test",
    srcs = ["speak_test.py"],
    deps = [
        ":sonora_speak_lib",
        "@pip//click",
    ],
)
